### ISSUE TITLE
Fix documentation tables in mobile

### ISSUE THREAD

**Issue by lifeiscontent** [fortitude/fortitude-docs#9]
currently hologram doesn't allow for easy customization of tables so this'll be a little bit of work, but I think its worth it to polish the mobile experience.

**Comment by agius** [comment]
Any reason not to move the docs to fortitude-sass repo? The less repos we have to manage, the better. Most gems I've looked at with documentation sites have the docs in the main repo - BS definitely does

**Comment by lifeiscontent** [comment]
@agius sounds reasonable. I don't mind it, just another feature though ;)
